global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spark-structured-streaming'
    metrics_path: /metrics/executors/prometheus
    static_configs:
      - targets: ['localhost:4040']

  - job_name: 'push_gateway_job'
    static_configs:
      - targets: ['localhost:9091']
